# Usa una imagen base de Node.js
FROM node:16

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia los archivos de tu proyecto al contenedor
COPY package*.json ./

# Instala las dependencias de Node.js
RUN npm install

# Copia el resto de los archivos de tu proyecto
COPY . .

# Exponer el puerto en el que la aplicación estará escuchando
EXPOSE 4013

# Comando para iniciar la aplicación
CMD ["npm", "start"]
