# Usar la imagen oficial de MongoDB
FROM mongo:latest

# Establecer directorio de trabajo
WORKDIR /data

# Copiar los archivos de datos y el script de inicialización
COPY stock.json /data/stock.json
COPY init-mongo.sh /docker-entrypoint-initdb.d/init-mongo.sh

# Dar permisos de ejecución al script
RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.sh

# Exponer el puerto de MongoDB
EXPOSE 27017
