# Usamos una imagen base de Node.js
FROM node:18

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar todos los archivos de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación escuchará
EXPOSE 4014

# Comando para iniciar la aplicación
CMD ["npm", "run", "dev"]
