# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia todo el contenido del proyecto al contenedor
COPY . .

# Expone el puerto en el que Vite correrá (por defecto, Vite corre en el 5173)
EXPOSE 5173

# Comando para iniciar la aplicación en modo de desarrollo
CMD ["npm", "run", "dev"]
