# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias para instalar primero las dependencias
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia todo el contenido del proyecto al contenedor
COPY . .

# Expone el puerto en el que Vite corre (5173 por defecto)
EXPOSE 5173

# Comando para iniciar la aplicación en modo de desarrollo (en tu entorno de contenedor)
CMD ["npm", "run", "dev", "--", "--host"]
