# Usar la imagen oficial de MongoDB como base
FROM mongo:latest

# Instalar el cliente de MongoDB
RUN apt-get update && apt-get install -y mongodb-org-shell


# Configuración del contenedor
WORKDIR /data
COPY products.json /data/products.json
COPY init-mongo.sh /docker-entrypoint-initdb.d/init-mongo.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.sh

EXPOSE 27017

