# Usar la imagen oficial de MongoDB como base
FROM mongo:latest

# Crear un directorio de trabajo dentro del contenedor
WORKDIR /data

# Copiar los archivos de datos y el script de inicialización
COPY products.json /data/products.json
COPY init-mongo.sh /docker-entrypoint-initdb.d/init-mongo.sh

# Asegurar que el script sea ejecutable
RUN chmod +x /docker-entrypoint-initdb.d/init-mongo.sh

# Exponer el puerto de MongoDB
EXPOSE 27017

# Comando de inicio del contenedor
CMD ["mongod", "--bind_ip_all", "--auth"]
