name: AWS Deployment for UpdateProduct Service

on:
  push:
    paths:
      - 'Backend/Domain/Products/UpdateProduct/**'
    branches: ["dev3"]
  pull_request:
    paths:
      - 'Backend/Domain/Products/UpdateProduct/**'
    branches: ["dev1", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build Backend/Domain/Products/UpdateProduct/ --file Backend/Domain/Products/UpdateProduct/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/update-product:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST_UPDATE_PRODUCT }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Deteniendo y eliminando contenedor previo..."
          sudo docker stop update-product || true
          sudo docker rm update-product || true

          echo "Actualizando imagen desde Docker Hub..."
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/update-product:latest

          echo "Ejecutando nuevo contenedor..."
          sudo docker run -d \
            --name update-product \
            -p 3012:3012 \
            -e MONGO_URI="mongodb://${{ secrets.EC2_HOST_MONGODB }}:27017/db_products" \
            ${{ secrets.DOCKER_USERNAME }}/update-product:latest
